# Generated by Django 4.0.5 on 2022-07-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('checkout', '0003_remove_orderdetails_items_orderitems_order_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='items_quantity',
            field=models.IntegerField(
                default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='total_price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='products.product'),
        ),
    ]
