# Generated by Django 4.0.5 on 2022-07-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_orderdetails_items_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
