# Generated by Django 4.0.5 on 2022-07-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderdetails_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='stripe_id',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
