# Generated by Django 4.0.5 on 2022-07-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderdetails_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.shippingaddress'),
        ),
    ]
